src/main/java/org/pio/sampleintern/web/model/HomeModel.java
package org.pio.sampleintern.web.model;

import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;
import org.springframework.format.annotation.NumberFormat;
import org.springframework.format.annotation.NumberFormat.Style;

import java.util.Date;

public class HomeModel
{
    // This is what I want to use instead of "style" -> pattern="#{messages['time.format']}"
    @DateTimeFormat(style = "S-")
    private DateTime today;

    @NumberFormat(style = Style.CURRENCY)
    private int size;

    private String language;

    public Date getTodayDate()
    {
        return today.toDate();
    }

    public int getSize()
    {
        return size;
    }

    public void setSize(int size)
    {
        this.size = size;
    }

    public String getLanguage()
    {
        return language;
    }

    public void setLanguage(String language)
    {
        this.language = language;
    }

    public DateTime getToday()
    {
        return today;
    }

    public void setToday(DateTime today)
    {
        this.today = today;
    }
}

src/main/java/org/pio/sampleintern/web/controller/BBQController.java
package org.pio.sampleintern.web.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * Other controller
 *
 * All Request to "/other" start here
 */
@Controller
@RequestMapping("/bbq")
public class BBQController {

    static final String BBQ_VIEW = "home/bbq";

    private static final Logger LOG = LoggerFactory.getLogger(BBQController.class);

    @RequestMapping(method = RequestMethod.GET)
    public String showPage() {
        LOG.debug("Accessing bbq page");
        return BBQ_VIEW;
    }

}

src/main/java/org/pio/sampleintern/web/controller/HomeController.java
package org.pio.sampleintern.web.controller;

import org.joda.time.DateTime;
import org.pio.sampleintern.web.model.HomeModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * Home Controller
 *
 * All Request to "/home" start here
 */
@Controller
@RequestMapping("/home")
public class HomeController {

    private static final Logger LOG = LoggerFactory.getLogger(HomeController.class);

    /**
     * No additional request value mapping, but forces to only GET requests
     *
     * @param model Model - Spring's model
     * @return String viewForInternalViewResolver
     */
    @RequestMapping(method = RequestMethod.GET)
    public String showHomePage(@ModelAttribute("model") HomeModel model) {
        LOG.info("Accessing main page");

        model.setToday(DateTime.now().minusDays(1));
        model.setSize(20000);

        return "home/home";
    }
}

src/main/java/org/pio/sampleintern/web/controller/OtherController.java
package org.pio.sampleintern.web.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * Other controller
 *
 * All Request to "/other" start here
 */
@Controller
@RequestMapping("/other")
public class OtherController {

    static final String OTHER_VIEW = "home/other";

    private static final Logger LOG = LoggerFactory.getLogger(OtherController.class);

    @RequestMapping(method = RequestMethod.GET)
    public String showPage() {
        LOG.debug("Accessing other page");
        return OTHER_VIEW;
    }

}

src/main/webapp/WEB-INF/jsp/common/common-head-elements.jspf
<meta charset="utf-8"/>

src/main/webapp/WEB-INF/jsp/decorators/empty.jsp
<%@include file="/WEB-INF/jsp/common/page-includes.jspf" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title><decorator:title default="Default Title" /></title>
        <meta name="abstract" content="empty"/>
        <decorator:head/>
    </head>
    <body>
        <decorator:body/>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/decorators/main.jsp
<%@include file="/WEB-INF/jsp/common/page-includes.jspf" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title><decorator:title default="Default Title" /></title>
        <meta name="abstract" content="main"/>

        <link href="${pageContext.request.contextPath}/site/css/base.css" rel="stylesheet" type="text/css" />

        <link rel="stylesheet/less" type="text/css" href="${pageContext.request.contextPath}/site/less/style.less">

        <script src="<c:url value="/site/js/jquery-1.7.1.min.js" /> "></script>
        <script src="<c:url value="/site/js/less-1.2.1.min.js" /> "></script>

        <decorator:head/>
    </head>
    <body>

    <div id="wrapper"><%-- contains everything that isn't the footer --%>

        <div id="primaryNavbar" class="navbar navbar-fixed-top"><div class="navbar-inner"><div class="container-fluid">
            <div id="party-block">
                <span class="party-name">Pio Corp</span>
            </div>

            <nav id="navLinks" role="navigation">
                <ul class="nav pills">
                    <li><a href="${pageContext.request.contextPath}/home"><spring:message code="nav.link.home"/></a></li>
                    <li><a href="${pageContext.request.contextPath}/bbq"><spring:message code="nav.link.bbq"/></a></li>
                    <li><a href="${pageContext.request.contextPath}/other"><spring:message code="nav.link.other"/></a></li>
                </ul>
            </nav>

        </div></div></div>

        <div id="content-body">
            <decorator:body/>
        </div>

    </div><%-- #wrapper/ --%>

    <footer id="footer">
        <small>&copy;2012 <span class="party-name">Pio design</span>
        </small>

    </footer>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/home/bbq.jsp
<%@include file="/WEB-INF/jsp/common/page-includes.jspf" %>
<html>
    <head>
        <title><spring:message code="bbq.browser.title"/></title>
        <%@include file="/WEB-INF/jsp/common/common-head-elements.jspf" %>
    </head>
    <body>
        <br> <spring:message code="bbq.page.lbl"/>
    </body>



</html>

src/main/webapp/WEB-INF/jsp/home/home.jsp
<%@include file="/WEB-INF/jsp/common/page-includes.jspf" %>
<html>
<head>
    <title><spring:message code="home.browser.title"/></title>
    <%@include file="/WEB-INF/jsp/common/common-head-elements.jspf" %>
    <script type="text/javascript" src="<c:url value="/site/js/jquery.cookies.2.2.0.js" /> "></script>
</head>
<body>
<%--<h3><spring:message code="home.page.title"/></h3>--%>

<h3>
    <spring:message code="home.page.language.lbl"/> &nbsp;
</h3>

<h2>Date Formatting</h2>

<h3>@DateTimeFormat(style="S-")</h3>
<p><spring:eval expression="model.today"/></p>
<small>This functionality is still limited!!!</small>
<p>
    @DateTimeFormat does not currently support l18n properties file support for custom date-format, the ticket was filed
    and is currently waiting here: <a href="https://jira.springsource.org/browse/SPR-8654">https://jira.springsource.org/browse/SPR-8654</a>
    and the
    desired useage is <a href="http://forum.springsource.org/showthread.php?113518-DateTimeFormat-and-pattern-i18n">http://forum.springsource.org/showthread.php?113518-DateTimeFormat-and-pattern-i18n</a>.
</p>
<br/><br/>

<spring:message code="time.format" var="datePattern" />
<h3>Spring EL version with &lt;fmt:formatDate pattern="${datePattern}" /&gt;</h3>
<p>
<fmt:formatDate value="${model.todayDate}" pattern="${datePattern}"/>
</p>

<br/><br/>
<h2>Currency and Numbers</h2>
<h3>Example: <spring:eval expression="model.size"/></h3>

<br/><br/><br/>
<form:form commandName="model" modelAttribute="model">
    <form:select id="language" path="language">
        <option value="en_US">English</option>
        <option value="fr_FR">French</option>
        <option value="pt_US">American Portuguese</option>
        <option value="pt_PO">Portugal Portuguese</option>
    </form:select>
</form:form>


<script type="text/javascript" charset="UTF-8">
    $(document).ready(function () {

        // Populate dropdown based on cookie language
        var language = $.cookies.get('org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE');
        $('#language')
                .val(language)
                .change(function () {
                    var newHref = window.location.href;
                    if (newHref.indexOf('?siteLanguage') > 0) {
                        newHref = newHref.substring(0, newHref.indexOf('?siteLanguage'));
                    }
                    newHref += '?siteLanguage=' + $('#language').val();
                    window.location.href = newHref;
                });
    });
</script>
</body>


</html>

src/main/webapp/WEB-INF/jsp/home/other.jsp
<%@include file="/WEB-INF/jsp/common/page-includes.jspf" %>
<html>
    <head>
        <title><spring:message code="other.browser.title"/></title>
        <%@include file="/WEB-INF/jsp/common/common-head-elements.jspf" %>
    </head>
    <body>
        <h3><spring:message code="other.page.title"/></h3>
        <br> <spring:message code="other.page.lbl"/>
    </body>



</html>